directories:
  output: release
  buildResources: build
appId: com.sistemaestoque.app
productName: SistemaEstoque
files:
  - filter:
      - '["out/**", "package.json"]'
mac:
  category: public.app-category.business
  extendInfo: '{ "NSHighResolutionCapable": "True" }'
win:
  target: '["nsis", "zip"]'
  icon: public/icon.ico
linux:
  target: '["AppImage", "deb"]'
  icon: public/icon.png
electronVersion: 43.4.1
